import "./globals.css";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";

import { Inter } from "next/font/google";
import { ProductProvider } from "./contexts/productContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Challenge La Nacion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProductProvider>{children}</ProductProvider>
      </body>
    </html>
  );
}
